//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonQ.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonQ.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型工厂错误，创建{0}类型出现异常：{1}.
        /// </summary>
        internal static string DataTypeFactory_CreateDerivedTypeError {
            get {
                return ResourceManager.GetString("DataTypeFactory_CreateDerivedTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型工厂错误，{0}的属性{1}的属性的set访问器异常.
        /// </summary>
        internal static string DataTypeFactory_EventAddAccessorError {
            get {
                return ResourceManager.GetString("DataTypeFactory_EventAddAccessorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型工厂错误，{0}的属性{1}的属性的set访问器异常.
        /// </summary>
        internal static string DataTypeFactory_EventRemoveAccessorError {
            get {
                return ResourceManager.GetString("DataTypeFactory_EventRemoveAccessorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型工厂错误，不支持{0}的未公开的方法{1}.
        /// </summary>
        internal static string DataTypeFactory_NonePublicMethodNotSupported {
            get {
                return ResourceManager.GetString("DataTypeFactory_NonePublicMethodNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型工厂错误，找不到{0}合适的构造方法.
        /// </summary>
        internal static string DataTypeFactory_NoSuitableConstructor {
            get {
                return ResourceManager.GetString("DataTypeFactory_NoSuitableConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型工厂错误，不支持此类型.
        /// </summary>
        internal static string DataTypeFactory_NotSupportedType {
            get {
                return ResourceManager.GetString("DataTypeFactory_NotSupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型工厂错误，{0}的属性{1}的get访问器异常.
        /// </summary>
        internal static string DataTypeFactory_PropertyGetAccessorError {
            get {
                return ResourceManager.GetString("DataTypeFactory_PropertyGetAccessorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型工厂错误，{0}的属性{1}的属性的set访问器异常.
        /// </summary>
        internal static string DataTypeFactory_PropertySetAccessorError {
            get {
                return ResourceManager.GetString("DataTypeFactory_PropertySetAccessorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，不支持数组类型：{0}.
        /// </summary>
        internal static string SqlClient_ArrayTypeNotSupported {
            get {
                return ResourceManager.GetString("SqlClient_ArrayTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，不支持当前绑定的对象类型：{0}.
        /// </summary>
        internal static string SqlClient_BindingTypeNotSupported {
            get {
                return ResourceManager.GetString("SqlClient_BindingTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，无法删除{0}，没有找到可以作为更新凭据的列(主键，标识，唯一索引，非空的GUID列)。.
        /// </summary>
        internal static string SqlClient_CanNotDeleteAsNoIdentityColumn {
            get {
                return ResourceManager.GetString("SqlClient_CanNotDeleteAsNoIdentityColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，无法识别的连接字符串：{0}.
        /// </summary>
        internal static string SqlClient_CanNotParseConnectionString {
            get {
                return ResourceManager.GetString("SqlClient_CanNotParseConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，无法读取数据集信息.
        /// </summary>
        internal static string SqlClient_CanNotReadSchema {
            get {
                return ResourceManager.GetString("SqlClient_CanNotReadSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，无法更新{0}，没有找到可以用于更新的列，请检查是否有足够的映射关系。.
        /// </summary>
        internal static string SqlClient_CanNotUpdateAsNoColumnForUpdate {
            get {
                return ResourceManager.GetString("SqlClient_CanNotUpdateAsNoColumnForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，无法更新{0}，没有找到可以作为更新凭据的列(主键，标识，唯一索引，非空的GUID列)或凭据列的值已经更改。.
        /// </summary>
        internal static string SqlClient_CanNotUpdateAsNoIdentityColumn {
            get {
                return ResourceManager.GetString("SqlClient_CanNotUpdateAsNoIdentityColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，不支持COM对象：{0}.
        /// </summary>
        internal static string SqlClient_COMObjectNotSupported {
            get {
                return ResourceManager.GetString("SqlClient_COMObjectNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，无法转换指定的类型：{0}.
        /// </summary>
        internal static string SqlClient_ConvertTypeNotSupported {
            get {
                return ResourceManager.GetString("SqlClient_ConvertTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，创建所需的派生类型{0}出现异常：{1}.
        /// </summary>
        internal static string SqlClient_CreateDerivedTypeError {
            get {
                return ResourceManager.GetString("SqlClient_CreateDerivedTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，创建所需的动态类型出现异常：{0}.
        /// </summary>
        internal static string SqlClient_CreateDynamicTypeError {
            get {
                return ResourceManager.GetString("SqlClient_CreateDynamicTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，不支持枚举对象类型：{0}.
        /// </summary>
        internal static string SqlClient_EnumTypeNotSupported {
            get {
                return ResourceManager.GetString("SqlClient_EnumTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，LINQ表达式的聚集函数的参数数量只能为2：{0}.
        /// </summary>
        internal static string SqlClient_ExpressionArgumentLengthError {
            get {
                return ResourceManager.GetString("SqlClient_ExpressionArgumentLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，不支持此LINQ成员表达式：{0}.
        /// </summary>
        internal static string SqlClient_ExpressionMemberNotSupported {
            get {
                return ResourceManager.GetString("SqlClient_ExpressionMemberNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，不支持此LINQ方法表达式：{0}.
        /// </summary>
        internal static string SqlClient_ExpressionMethodNotSupported {
            get {
                return ResourceManager.GetString("SqlClient_ExpressionMethodNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，不支持此LINQ表达式的类型.
        /// </summary>
        internal static string SqlClient_ExpressionTypeNotSupported {
            get {
                return ResourceManager.GetString("SqlClient_ExpressionTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，记录不存在列{0}.
        /// </summary>
        internal static string SqlClient_NameNotExistsInRecord {
            get {
                return ResourceManager.GetString("SqlClient_NameNotExistsInRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，无法删除实体，没有对应命令.
        /// </summary>
        internal static string SqlClient_NoDeleteCommand {
            get {
                return ResourceManager.GetString("SqlClient_NoDeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，不支持当前节点类型.
        /// </summary>
        internal static string SqlClient_NodeTypeNotSupported {
            get {
                return ResourceManager.GetString("SqlClient_NodeTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，无法插入实体，没有对应命令.
        /// </summary>
        internal static string SqlClient_NoInsertCommand {
            get {
                return ResourceManager.GetString("SqlClient_NoInsertCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，没有合适的构造方法.
        /// </summary>
        internal static string SqlClient_NoSuitableConstructor {
            get {
                return ResourceManager.GetString("SqlClient_NoSuitableConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，不支持此功能.
        /// </summary>
        internal static string SqlClient_NotSupported {
            get {
                return ResourceManager.GetString("SqlClient_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，无法更新实体，没有对应命令.
        /// </summary>
        internal static string SqlClient_NoUpdateCommand {
            get {
                return ResourceManager.GetString("SqlClient_NoUpdateCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，无法识别的连接字符串：{0}.
        /// </summary>
        internal static string SqlClient_ParseConnectionStringError {
            get {
                return ResourceManager.GetString("SqlClient_ParseConnectionStringError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，MonQ提供的LINQ查询不支持与非MonQ提供的查询分析器进行连接：{0}.
        /// </summary>
        internal static string SqlClient_QuerySourceNotSupported {
            get {
                return ResourceManager.GetString("SqlClient_QuerySourceNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，回写参数{0}，索引{1}，值：{2}，出现异常。.
        /// </summary>
        internal static string SqlClient_RetrieveParameterError {
            get {
                return ResourceManager.GetString("SqlClient_RetrieveParameterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，类型不能封闭.
        /// </summary>
        internal static string SqlClient_SealedTypeNotSupported {
            get {
                return ResourceManager.GetString("SqlClient_SealedTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，必须是公开的类型.
        /// </summary>
        internal static string SqlClient_TypeMustBePublic {
            get {
                return ResourceManager.GetString("SqlClient_TypeMustBePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，不支持的类型{0}.
        /// </summary>
        internal static string SqlClient_TypeNotSupported {
            get {
                return ResourceManager.GetString("SqlClient_TypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，无法识别的排序规则{0}.
        /// </summary>
        internal static string SqlClient_UnknownOrderRule {
            get {
                return ResourceManager.GetString("SqlClient_UnknownOrderRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL客户端错误，不支持值类型.
        /// </summary>
        internal static string SqlClient_ValueTypeNotSupported {
            get {
                return ResourceManager.GetString("SqlClient_ValueTypeNotSupported", resourceCulture);
            }
        }
    }
}
